---
- hosts: server
  tasks:
    - name: run Maven build - resolves dependencies
      shell: mvn build
    - name: run Maven clean install - creates actual jar/war file
      shell: mvn clean install
